
parameters:
  s3url: '%env(S3_URL)%'
  sqsurl: '%env(SQS_URL)%'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  App\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
  acme_api.event.authentication_failure_listener:
    class: App\EventListener\AuthenticationFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
  acme_api.event.authentication_success_listener:
    class: App\EventListener\AuthenticationSuccessListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
  Aws\S3\S3Client:
    arguments:
      - version: 'latest'
        region: 'ap-southeast-1'
        credentials:
          key: '%env(S3_KEY_ID)%'
          secret: '%env(AWS_SECRET)%'
  Aws\Sqs\SqsClient:
    arguments:
      - version: 'latest'
        region: 'ap-southeast-1'
        credentials:
          key: '%env(S3_KEY_ID)%'
          secret: '%env(AWS_SECRET)%'
  App\Manager\FileManager:
    arguments:
      $targetDirectory: '%kernel.project_dir%/public/upload/image/'
      $bucketName: '%env(S3_BUCKET_NAME)%'